<a href="https://colab.research.google.com/github/RansikaG/EN2550---Machine-Vision/blob/main/1_Tensorflow_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x = tf.Variable(3.0)

In [3]:
with tf.GradientTape() as tape:
  y = x * x

In [4]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

In [5]:
tape.gradient(y, x)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [6]:
x = tf.Variable([
  [1.0, -1.0, 2.0, 4.0],
  [-2.0, 3.0, -5.0, 9.0],
  [4.0, 2.0, 3.0, 9.0],                
  [1.0, 5.0, 6.0, 3.0],                

])
t = 30.0

In [7]:
with tf.GradientTape() as tape:
  a = tf.nn.max_pool2d(tf.reshape(x, (1, 4, 4, 1)), ksize=2, strides=2, padding="VALID")
  b = tf.reduce_sum(a)
  error = 0.5 * (b - t) ** 2

In [8]:
a

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[3.],
         [9.]],

        [[5.],
         [9.]]]], dtype=float32)>

In [9]:
error

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [10]:
tape.gradient(error, [b, x])

[<tf.Tensor: shape=(), dtype=float32, numpy=-4.0>,
 <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[ 0.,  0.,  0.,  0.],
        [ 0., -4.,  0., -4.],
        [ 0.,  0.,  0., -4.],
        [ 0., -4.,  0.,  0.]], dtype=float32)>]